version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=bertrandmakaya
      - POSTGRES_PASSWORD=Ksy2RMUg4BWk7wL15a!
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5435:5435'
volumes:
  postgres:
